_BASE_: "../../Base-RCNN-C4-OWOD.yaml"
MODEL:
  WEIGHTS: "/home/tjl/OWOD/output/t3_ft/model_final.pth"
  ROI_HEADS:
    NUM_CLASSES : 24
DATASETS:
  TRAIN: ('t3_voc_coco_2007_ft', )
  TEST: ('voc_coco_2007_test', )
SOLVER:
  STEPS: (110000, 112000)
  MAX_ITER: 116500
  WARMUP_ITERS: 0
OUTPUT_DIR: "./output/t3_ft_baseline"
OWOD:
  PREV_INTRODUCED_CLS: 15
  CUR_INTRODUCED_CLS: 4
  ENABLE_CLUSTERING: False
  CLUSTERING:
    START_ITER: 74000