_BASE_: "/home/tjl/OWOD/configs/PascalVOC-Detection/faster_rcnn_R_50_C4.yaml"
MODEL:
  WEIGHTS: "/home/tjl/OWOD/output/t2_ft/model_final.pth"
  ROI_HEADS:
    NUM_CLASSES : 24
DATASETS:
  TRAIN: ('voc_coco_2007_val', ) # t1_voc_coco_2007_train, t1_voc_coco_2007_ft
  TEST: ('voc_coco_2007_val', )
SOLVER:
  STEPS: (50000, 60000)
  MAX_ITER: 500
  WARMUP_ITERS: 0
OUTPUT_DIR: "./output/t2_val"
OWOD:
  PREV_INTRODUCED_CLS: 10
  CUR_INTRODUCED_CLS: 5
  ENABLE_CLUSTERING: False
  COMPUTE_ENERGY: False
  ENERGY_SAVE_PATH: 'energy'
  SKIP_TRAINING_WHILE_EVAL: False