_BASE_: "../../Base-RCNN-C4-OWOD.yaml"
MODEL:
  WEIGHTS: "/home/tajl/OWOD/output/t4_ft/model_final.pth"
  ROI_HEADS:
    NUM_CLASSES : 24
DATASETS:
  TRAIN: ('t4_voc_coco_2007_ft', )
  TEST: ('voc_coco_2007_test', )
SOLVER:
  STEPS: (155500, 156500)
  MAX_ITER: 160500
  WARMUP_ITERS: 0
OUTPUT_DIR: "./output/t4_ft"
OWOD:
  PREV_INTRODUCED_CLS: 19
  CUR_INTRODUCED_CLS: 4
  ENABLE_CLUSTERING: False
  CLUSTERING:
    START_ITER: 116500