_BASE_: "../../Base-RCNN-C4-OWOD.yaml"
MODEL:
  WEIGHTS: "/home/tjl/OWOD/output/t2_ft/model_final.pth"
  ROI_HEADS:
    NUM_CLASSES : 24
DATASETS:
  TRAIN: ('t2_voc_coco_2007_ft', ) # t1_voc_coco_2007_train, t1_voc_coco_2007_ft
  TEST: ('voc_coco_2007_test', )
SOLVER:
  STEPS: (50000, 60000)
  MAX_ITER: 74000
  WARMUP_ITERS: 0
OUTPUT_DIR: "./output/t2_ft"
OWOD:
  PREV_INTRODUCED_CLS: 10
  CUR_INTRODUCED_CLS: 5
  ENABLE_CLUSTERING: False
  ENABLE_THRESHOLD_AUTOLABEL_UNK: False
  CLUSTERING:
    START_ITER: 18000