_BASE_: "../../Base-RCNN-C4-OWOD.yaml"
MODEL:
  WEIGHTS: "/home/fk1/workspace/OWOD/output/t2_baseline/model_final.pth"
DATASETS:
  TRAIN: ('t2_voc_coco_2007_train', )
  TEST: ('voc_coco_2007_test', )
SOLVER:
  STEPS: (23000,27000) #(50000, 60000)
  MAX_ITER: 28000
  WARMUP_ITERS: 0
OUTPUT_DIR: "./output/t2_baseline"
OWOD:
  PREV_INTRODUCED_CLS: 10
  CUR_INTRODUCED_CLS: 5
  ENABLE_THRESHOLD_AUTOLABEL_UNK: False
  ENABLE_CLUSTERING: False